const express = require("express")
const app = express()
const bodyParser = require("body-parser")
const dotenv = require('dotenv').config()
const cookieParser = require('cookie-parser')
const helmet = require('helmet')
const cors = require('cors')
const logger = require('morgan')
const compression = require('compression')
const pages = require('./routes/pages')
const auth = require('./routes/auth')
const user = require("./routes/users")
const {error404,error500} = require('./middlewares/errorhandler')

app.use(express.static("public"))
app.use(express.json())
app.use(bodyParser.urlencoded({extended:true}))
app.use(bodyParser.json())
app.use(cookieParser())
app.use(helmet())
app.use(cors())
app.use(logger('dev'))
app.use(compression())

app.use('/api/v1',pages)
app.use('/api/v1/auth',auth) 
app.use('/api/v1/user',user)
app.use(error404)
app.use(error500)

module.exports = app